version: 1
from: "infracamp/kickstart-flavor-gaia:testing"

apache_fallback_resource: "/index.php"

http_port: 4000

config_file:
  template: config.php.dist
  target: config.php


command:
  build:
    - "echo \"www-data   ALL = (ALL) NOPASSWD: /usr/bin/docker\" | sudo tee --append /etc/sudoers"
    - "sudo apt-get -y install nginx docker.io"
    - "composer update"


  run:
    - "/opt/bin/update-nginx.php"

  interval:
    - "/opt/bin/update-nginx.php"
