version: 1
from: "infracamp/kickstart-flavor-gaia:testing"

apache_fallback_resource: "/index.php"
http_port: 4000

config_file:
  template: config.php.dist
  target: config.php


command:
  build:
    - "echo \"www-data   ALL = (ALL) NOPASSWD: /usr/bin/timeout\" | sudo tee --append /etc/sudoers"
    - "echo \"www-data   ALL = (ALL) NOPASSWD: /usr/bin/docker\" | sudo tee --append /etc/sudoers"
    #- "echo \"www-data   ALL = (ALL) NOPASSWD: /usr/bin/docker service\" | sudo tee --append /etc/sudoers"
    - "sudo apt-get -y install nginx docker.io"
    - "sudo rm /var/www/html/index.nginx-debian.html"
    - "sudo rm /etc/nginx/sites-enabled/default"
    - "composer update"


  run:
    - "sudo /opt/bin/update-nginx.php"

  interval:
    - "sudo /opt/bin/update-nginx.php || true"
